training:
  epochs: 200
  patience: 30

image:
  imgsz: 1920
  batch: 2
  # amp: true

augmentation:
  hsv_h: 0.5
  hsv_s: 0.7
  hsv_v: 0.5

  degrees: 100.0
  translate: 0.4
  scale: 0.4
  shear: 5.0

  mosaic: 0.8

  mixup: 0.2
  copy_paste: 0.15

  flipud: 0.34
  fliplr: 0.48

optimizer:
  optimizer: AdamW

  lr0: 0.0003
  lrf: 0.01

  weight_decay: 0.0005