training:
  epochs: 200
  patience: 80
  warmup_epochs: 3 # https://arxiv.org/abs/1910.08475
  pretrained: true

amp:
  amp: true

image:
  imgsz: 1280
  multi_scale: false

configs:
  batch: -1 # safer with high resolution
  freeze: 5
  nbs: 64

augmentation:
  hsv_h: 0.00701
  hsv_s: 0.77123
  hsv_v: 0.41418

  degrees: 10
  translate: 0.1
  scale: 0.5
  shear: 0.0

  close_mosaic: 20
  mosaic: 0.5
  mixup: 0.05
  copy_paste: 0.1

  erasing: 0.4

optimizer:
  optimizer: AdamW
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005

loss:
  box: 7.5
  cls: 1.0
  dfl: 1.5

logging:
  verbose: true
  plots: true

save_results:
  project: "YOLO_HAND_WRITING_STAGE2"
